modLoader="javafml"
loaderVersion="[37,)"
license="All rights reserved"
issueTrackerURL="https://discord.gg/pHren9yxzW"
[[mods]]
    modId="divedeeper"
    version="1.17.1-0.2"
    displayName="Dive Deeper"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/dive-deeper"
    authors="SSKirillSS"
    description = '''Mod about increased difficulty in the depths of the world'''
[[dependencies.divedeeper]]
    modId = "forge"
    mandatory = true
    versionRange = "[37,)"
    ordering = "NONE"
    side = "BOTH"
